### ISSUE TITLE
Create Mission Statement and upload to all appropriate places

### ISSUE THREAD

**Issue by dfackler** [codefordenver/org#83] opened 2017-03-07 03:04 UTC
Create mission statement to aid fundraising marketing campaign and general understanding of organization. 

Get sign-off from heads.

**Comment by Mira321** [comment] 2017-03-28 01:18
Type up the Mission statement and put it in the the Org folder

**Comment by Mira321** [comment] 2017-03-28 01:18
Upload it to the web site

**Comment by Mira321** [comment] 2017-03-28 01:19
Put the mission on the agenda.

**Comment by wdoug** [comment] 2017-04-11 00:51
> "Volunteer-driven, community outreach that improves people’s lives through technology"

**Comment by ideaSandboxInDenver** [comment] 2017-04-11 18:35
This is a duplicate of the post I added to Flowdock.

Hello there. I updated the CfD website:

Updated the projects on the CfD [site]( http://www.codefordenver.org/WhatWeDo) (I don't have new images for the slideshow)

Added a [Mission Statement Voting Results](https://docs.google.com/document/d/12_R3f7Ymfe8oIszqvPiztePF_7A1Jlpfa7JKzZU6LeU/edit?usp=sharing) Page to Google Docs:

Added the Mission Statement in its own Google [Doc](https://docs.google.com/document/d/1ZihgNmJ61dBEHnh9odQyYAzS8jWXQp-0E8k2tFRtmlw/edit?usp=sharing):

I used **Suggest Edit** on the site and these need to be approved.

Thank you (Willy) for updating the agenda to include the Mission Statement.

**Closed** 2017-05-09 01:24 UTC
Labels: Process
